##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: Megan Rodgers Military Collection Exhibit
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Showcasing the service of a female military linguist.
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Secret Squirrel, Ghost, Spook. These are all nicknames for military linguists, an under-the-radar and lesser-known enlisted job. Their job is so top secret, even they don’t know what they’re doing! Just kidding :). 

Military linguists are highly trained, intelligent members of the armed forces. They can operate behind the scenes or right in the thick of things. This exhibit of the Megan C. Rodgers military collection exhibit showcases the abilities and achievements of a female service member’s career in a male-dominated field such as aviation. 

We invite you to explore selected uniform items, photos, and documents from Megan’s enlistment and ask yourself if you would have what it takes. 

We hope you enjoy seeing how this Sailor joined the Navy and saw the world!"

# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Megan Rodgers

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: mr-military

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
